name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'production'

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    name: Assemble
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.ACCESS_TOKEN }}

      - name: Build Project
        run: ./gradlew build

      - name: Extract Version Info
        run: |
          export ARTIFACT_VERSION=$(./gradlew properties | grep ^version | cut -c 10-)
          echo "ARTIFACT_VERSION=$ARTIFACT_VERSION" >> $GITHUB_ENV

      - name: Tag Release
        run: |
          git tag -a ${{ env.ARTIFACT_VERSION }} -m "Release v${{ env.ARTIFACT_VERSION }}"
          git push origin ${{ env.ARTIFACT_VERSION}}